# if "headless" then browser does not visibly open, otherwise browser opens
mode: ""

# Log file location
logfile: "no_more_waitlist.log"

# MyCarleton Username/Password
login:
  username: "Your username"
  password: "Your password"

# Sample structure:
# terms:
#     - YYYYTT (ie. "201930" for 2019 Fall, or "202020" for 2020 Summer, or "202110" for 2021 Winter)
#       - Course CRN
#       - Course CRN
